add while

diff --git a/.github/workflows/robot.yml b/.github/workflows/robot.yml
--- a/.github/workflows/robot.yml
+++ b/.github/workflows/robot.yml
@@ -26,12 +26,22 @@ jobs:
         run: |
           cd robot
           docker-compose up -d
-          while [ -f reports/xunit.xml ]
+          timeout=10
+          while [ ! -f reports/xunit.xml ];
           do
-            docker-compose down
-            ${{ env.l1-test-check }}=true
-            echo "[ Robot-Debug ] l1-testing is finished"
+            if [ "$timeout" == 0 ]; then
+              docker-compose down
+              echo "ERROR: Timeout while waiting for the file reports/xunit.xml."
+              exit 1
+            fi
+            sleep 1
+            ((timeout--))
+            echo "[ Robot-Debug ] waiting for reports generate: $timeout s"
           done
+          docker-compose down
+          ${{ env.l1-test-check }}=true
+          echo "[ Robot-Debug ] reports/xunit.xml file found"
+          echo "[ Robot-Debug ] l1-testing is finished"
           cd -
 
       - name: l1-test report check
